### PR TITLE
hotfix/account error and colors

### PR DESCRIPTION
**Pull request by mandresm**
This solves issue #esm-tools/esm_tools#334.

I am wondering if the place where I made the fix is the best place. The idea is that we want to notify the user on a clear way that they are missing the `account` variable in their runscript, but there are some systems (i.e. `ollie`) that do not need the `account` variable. I thought it would be better to have a check inside `esm_runscripts` but then we need to dig into the computer info (see lines below) to check if the `account` variable is required:

In `slurm.yaml`
https://github.com/esm-tools/esm_tools/blob/5369581243f43663e48e6accb3c5966dbf5bc2e1/configs/other_software/batch_system/slurm.yaml#L21-L23

@denizural , @pgierz , what do you think about this alternative fix in the `esm_parser`? Potentially too little generalized or the way to go?

### CODE REVIEW

**Comment by pgierz** [comment]
Runscripts would be the more "correct" place to put this, but I think you are right Miguel, that might be too involved. As a workaround, we can put it here, and add a "not needed" default to the account setting on ollie in the machine yaml. Maybe that would solve it?

**Comment by mandresm** [comment]
> Runscripts would be the more "correct" place to put this, but I think you are right Miguel, that might be too involved. As a workaround, we can put it here, and add a "not needed" default to the account setting on ollie in the machine yaml. Maybe that would solve it?

These lines are not reached for `ollie` as `accounting` variable is set `False`, so the account flag is never used. So i think there is nothing to solve in `ollie` unless I did not understand your comment correctly...

Anyway, I could add the same functionality relatively easily in `esm_runscripts`. After all we just need to check if `accounting` is true, and if it is show an error in case there is no `account` defined. I think I'm leaning more towards that solution now.

**Comment by denizural** [comment]
Just few heads-up:
- don't forget to add `colorama` into `setup.py`, `requirements` section.
- add colorama.init(autoreset=True) to prevent escape sequences printed when the `esm_runscripts` output is redirected.
Eg. 
```python
print(f"{colorama.Fore.RED}hello {colorama.Fore.GREEN}world")
```
may result in `^[[31mhello ^[[32mworld`

**Comment by mandresm** [comment]
> Just few heads-up:
> 
>     * don't forget to add `colorama` into `setup.py`, `requirements` section.
> 
>     * add colorama.init(autoreset=True) to prevent escape sequences printed when the `esm_runscripts` output is redirected.
>       Eg.
> 
> 
> ```python
> print(f"{colorama.Fore.RED}hello {colorama.Fore.GREEN}world")
> ```
> 
> may result in `^[[31mhello ^[[32mworld`

I thought the `colorama.Style.RESET_ALL` will deal with it too:
https://github.com/esm-tools/esm_parser/pull/60/files#diff-27c94fed5ee1583631f97e1da4def7389849469e195a95948f2e4d24b9125fa5R2587

**Comment by denizural** [comment]
`colorama.Style.RESET_ALL` works but you need to put that to the end of each print. Which could be bit cumbersome. Using `init(autoreset=True)` is an easier option. It automatically terminates each print statement with a RESET_ALL for you.

**Comment by mandresm** [comment]
Okay, thanks for the clarification :)

**Comment by mandresm** [comment]
After the last changes this is not a hotfix anymore for the account issue, but just adding colors to the `user_error` and `user_note` methods. Therefore, this will be merged to `develop` only.

**Pull request merged**
