### PR TITLE
functionality to search for duplicates in yaml files and incompatible _changes added

### PR DESCRIPTION
**Pull request by mandresm**
The issue was that if you have two `namelist_changes`  inside the same file, only the last one is chosen. That is partly the reason why we have the `add_namelist_changes` option, which adds modifications instead of completely overriding `namelist_changes`. In order to prevent errors as the `dt_start` (issue esm-tools/esm_tools#130) I added a functionality that checks for repetitions of  variables containing `_changes` (but excluding the ones with ``add_``) inside the same file (when same `_changes` are present in different files it works already as desired). After finding a repetition of `_changes` or incompatible `_changes` (same `_changes` that are in non-exclusive `choose_`)  it throws an error.

**Additionally this hotfix looks for duplicates inside yaml files** and returns an error if it finds some.

@seb-wahl, there are some duplicates in `oifs.yaml` found by executing:
```
esm_master
```

After your review, and if you agree with the changes, could you please fix the `oifs.yaml`?

### CODE REVIEW

**Comment by mandresm** [comment]
I also added a `find_key` method in `esm_parser.py`. It basically looks for keys in a dictionary containing a given string, or being an integer/float. It then returns the path in the dictionary to the keys that coincide with the condition specified. I needed this for searching for ``_changes`` and ``choose`` but I generalized it and place it in ``esm_parser.py`` (instead of in ``yaml_to_dict.py) because it might be useful for other applications.

**Comment by denizural** [comment]
As we mentioned during the group meeting, maybe some of the exception raises can be replaced with a `error prints + sys.exit()` since the default behaviour is printing the (lengthy) error stack which can be confusing to the user.

**Comment by mandresm** [comment]
Thanks, I'll be adding a method in esm_parser to report clearer errors using `print` + `sys.exit()`.

**Comment by mandresm** [comment]
Errors look like this now:

```
YAML syntax error!
------------------

The general ``namelist_changes`` and ``_changes`` in ``choose_`` are not compatible in /home/ollie/mandresm/esm_tools/configs/components/echam/echam.yaml:
    - choose_lresume.True.namelist_changes
    - choose_CO2.*.namelist_changes
    - choose_CH4.*.namelist_changes
    - choose_N2O.*.namelist_changes
    - choose_CECC.*.namelist_changes
    - choose_COBLD.*.namelist_changes
    - choose_CLONP.*.namelist_changes
    - choose_yr_perp_off.True.namelist_changes

Note that if there are more than one ``_changes`` in the file, they need to be placed inside different cases of the same ``choose`` and these options need to be compatible (only one ``_changes`` can be reached at a time).
Use ``add_<variable>_changes`` if you want to add/overwrite variables inside the main ``_changes``.
```

**Comment by seb-wahl** [comment]
I still get an error message that is different to what you have. It tells me what's wrong but still has an uncaught python error stack.
```bash
blogin3:~/esm/esm_tools $ esm_master
Traceback (most recent call last):
  File "/home/shkifmsw/.local/bin/esm_master", line 10, in <module>
    sys.exit(main())
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/cli.py", line 74, in main
    main_flow(parsed_args, target)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/esm_master.py", line 27, in main_flow
    setups2models = setup_and_model_infos(vcs, main_infos, parsed_args)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/compile_info.py", line 336, in __init__
    self.config = combine_components_yaml()
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/compile_info.py", line 92, in combine_components_yaml
    asyncio.get_event_loop().run_until_complete(get_all_package_info(os.listdir(cat_dir), cat, cat_dir, components_dict, relevant_entries))
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/compile_info.py", line 130, in get_all_package_info
    await asyncio.gather(*tasks, return_exceptions=False)
  File "/home/shkifmsw/.local/lib/python3.7/site-packages/esm_master/compile_info.py", line 159, in get_one_package_info
    comp_config = esm_parser.yaml_file_to_dict(default_file)
  File "/home/shkifmsw/gitlab/esm_parser/esm_parser/yaml_to_dict.py", line 39, in yaml_file_to_dict
    check_duplicates(yaml_file)
  File "/home/shkifmsw/gitlab/esm_parser/esm_parser/yaml_to_dict.py", line 250, in check_duplicates
    return yaml.load(src, Loader=PreserveDuplicatesLoader)
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/site-packages/yaml/constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/site-packages/yaml/constructor.py", line 47, in construct_document
    data = self.construct_object(node)
  File "/sw/tools/anaconda3/2019.10/skl/lib/python3.7/site-packages/yaml/constructor.py", line 92, in construct_object
    data = constructor(self, node)
  File "/home/shkifmsw/gitlab/esm_parser/esm_parser/yaml_to_dict.py", line 243, in map_constructor
    .format(key, str(key_node.start_mark).replace("  ","").split(",")[0]))
yaml.constructor.ConstructorError: pping
  in "/home/shkifmsw/esm/esm_tools/configs/components/oifs/oifs.yaml", line 5, column 1


Key ``runtime_environment_changes`` is duplicated in "/home/shkifmsw/esm/esm_tools/configs/components/oifs/oifs.yaml"


blogin3:~/esm/esm_tools $ esm_versions check
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.2
esm_parser: 4.2.1 (development install, on branch: hotfix/check_duplicates_yaml, describe=v4.2.1-5-gb3e2a76)
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1 (development install, on branch: develop, describe=v4.2.1-13-g8af582f)
esm_tools: 4.2.3 (development install, on branch: feature/add-oifs-43r3-v1, describe=v4.2.2-28-gd561e2f)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
blogin3:~/esm/esm_tools $
```

**Comment by mandresm** [comment]
I forgot about the duplicated variable error. Now it should work as intended.

**Comment by seb-wahl** [comment]
I can verify that it works now as intended. I told my folks to push all their changes to oifs.yaml, so I can then build a clean oifs.yaml. I think we shouldn't push it to release until it works with the release branch of esm_tools. Otherwise new users will download the tools, type `esm_master` and are confronted with an error message.

**Review by seb-wahl — APPROVED** [review]
Looks good and works for me. But don't push to release until we have removed all duplicates that are now detected from the release and develop branch of `esm_tools`

**Comment by mandresm** [comment]
Agreed :)

**Pull request merged**
