### PR TITLE
feature/EsmToolsDir class

### PR DESCRIPTION
**Pull request by mandresm**
**Note**: not be reviewed yet (review only when the TODO list is checked out :) )

Puts esm-tools/esm_rcfile#2 into use:

Now, the variables `${esm_configs_dir}`, `${esm_runscripts_dir}` and `${esm_namelist_dir}` are an EsmToolsDir instance that "waits" until they are called by another variable (i.e. `method: ${esm_configs_dir}/path_to_your_preprocessing_script`) to find the adequate path depending if the run is open or occurs inside a virtual environment.

**Requires**
- esm-tools/esm_rcfile#2
- esm-tools/esm_tools#279

**TODO**
- [x] Testing with `oifs` preprocessing for an open run
- [x] Testing with `oifs` preprocessing for a run with venv
- [x] Remove the unnecessary `NONE_YET` blocks in all the packages
- [x] AWICM3 test
- [x] AWICM1 test

### CODE REVIEW

**Review by dbarbi — APPROVED** [review]
Will merge by hand right now

**Comment by dbarbi** [comment]
Actually I won't as Miguel is putting in something else

**Comment by mandresm** [comment]
Tested for AWICM-3 and AWICM-1, both for open run and virtual environment. All test succeeded on restarting, producing outdata and moving the files to the correct folders.

In the AWICM-3 venv test the following variables were defined inside the runscript:
```
    sometesting:
            function: ${general.esm_function_dir}
            namelist: ${general.esm_namelist_dir}
            runscript: ${general.esm_runscript_dir}
            functions: ${general.esm_function_dir}s
            namelists: ${general.esm_namelist_dir}s
            runscripts: ${general.esm_runscript_dir}s
            sfunctions: s${general.esm_function_dir}s
            snamelists: s${general.esm_namelist_dir}s
            srunscripts: s${general.esm_runscript_dir}s
```

These variables, in the `config/*finished*.yaml` are defined correctly (`esm_tools` installation is editable inside the venv, and that's why these paths point at `src` folder instead of the `.venv_esmtools`):
```
    sometesting:
      function: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/configs/
      functions: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/configs/s
      namelist: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/namelists/
      namelists: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/namelists/s
      runscript: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/runscripts/
      runscripts: /work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/runscripts/s
      sfunctions: s/work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/configs/s
      snamelists: s/work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/namelists/s
      srunscripts: s/work/ollie/mandresm/esm_yaml_test/awicm3_ETD_venv/src/esm-tools/esm_tools/runscripts/s
```

**Comment by mandresm** [comment]
Ready to be merged together with esm-tools/esm_runscripts#80

**Comment by dbarbi** [comment]
will be merged now

**Pull request merged**
